name: Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [master]
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test-ci

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install playwright
        run: npx playwright install

      - name: Run e2e tests
        run: npm run e2e-ci